### CRIAR COMPETIÇÃO
POST https://desafio-estante-virtual.herokuapp.com/competition
Content-Type: application/json

{
    "name": "100m",
    "status": "Não inicializada"
}

### CRIAR ATLETA

POST https://desafio-estante-virtual.herokuapp.com/athlete
Content-Type: application/json

{
    "name": "Amanda"
}
### BUSCAR TODAS AS COMPETIÇÕES
GET https://desafio-estante-virtual.herokuapp.com/competitions

### BUSCAR TODOS OS ATLETAS
GET https://desafio-estante-virtual.herokuapp.com/athletes

### CADASTRAR RESULTADO
POST https://desafio-estante-virtual.herokuapp.com/play/db79bf54-209a-45b2-a9c4-395346342d68/e671efb3-1d81-49bb-8133-4e41425d23f5
Content-Type: application/json

{
    "value": [86.9, 87.4, 88],
    "unity": "m"
}

### BUSCAR RANKING PELO ID DA COMPETIÇÃO 
GET https://desafio-estante-virtual.herokuapp.com/db79bf54-209a-45b2-a9c4-395346342d68


### FINALIZAR UMA COMPETIÇÃO
PUT https://desafio-estante-virtual.herokuapp.com/competition/a6b77efd-c1cd-4c5c-8f50-b3a4eca917a7
