### CRIAR COMPETIÇÃO
POST http://localhost:3003/competition
Content-Type: application/json

{
    "name": "100m",
    "status": "Acontecendo agora"
}


### CRIAR ATLETA

POST http://localhost:3003/athlete
Content-Type: application/json

{
    "name": "Pedro"
}

### CADASTRAR RESULTADO
POST http://localhost:3003/play/ab2a2e7d-3e40-476c-8363-674dc7e2e5c5/5eabcb76-c93c-4f0b-92bd-c2aea2d08a11
Content-Type: application/json

{
    "value": 85,
    "unity": "s"
}

### FINALIZAR UMA COMPETIÇÃO
PUT http://localhost:3003/competition/74f195fb-a060-4f83-bd0f-f99d1a69eba2

### BUSCAR RESULTADO PELO ID DA COMPETIÇÃO 
GET http://localhost:3003/ab2a2e7d-3e40-476c-8363-674dc7e2e5c5