### CRIAR COMPETIÇÃO
POST http://localhost:3003/competition
Content-Type: application/json

{
    "name": "Lançamento de dardo",
    "status": "Acontecendo agora"
}

### CRIAR ATLETA

POST http://localhost:3003/athlete
Content-Type: application/json

{
    "name": "Alice"
}
### BUSCAR TODAS AS COMPETIÇÕES
GET http://localhost:3003/competitions

### BUSCAR TODOS OS ATLETAS
GET http://localhost:3003/athletes

### BUSCAR RANKING PELO ID DA COMPETIÇÃO 
GET http://localhost:3003/4614ed32-795d-487e-9cce-95308bd14249

### CADASTRAR RESULTADO
POST http://localhost:3003/play/4614ed32-795d-487e-9cce-95308bd14249/aeb4e458-90ba-43c3-9202-578ba85b0446
Content-Type: application/json

{
    "value": [101.3, 99.8, 102],
    "unity": "m"
}

### FINALIZAR UMA COMPETIÇÃO
PUT http://localhost:3003/competition/d09f660d-bc72-44c2-a0ac-051949ac6964
