@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ1OGI4NDA4LWI3OGQtNGEzNi1hOTEyLWZkM2NhMjhkOGRkZSIsImlhdCI6MTY1NzE1NjA1NCwiZXhwIjoxNjU3MTU5NjU0fQ.jjqFg_Qz1OgAlT_phTwtucZ3KN7e39LG8qu8H7QVOMU

POST http://localhost:3003/user/signup
 Content-Type: application/json

 {
    "name":"Gaules",
    "email":"gaul@gmail.com",
    "password":"02121983"
 } 

###

POST http://localhost:3003/user/login
 Content-Type: application/json

 {
    "email":"gaul@gmail.com",
    "password":"02121983"
 } 

###
POST http://localhost:3003/post
Authorization: {{token}}
Content-Type: application/json

{
   "photo": "https://culturalizabh.com.br/wp-content/uploads/2021/07/218283699_496391104792100_6873675953089983584_n-1024x683.jpg",
   "description": "Comida japonesa",
   "type": "NORMAL",
   "author_id": "f73cdb13-e4bc-4c07-9930-241a264e4241"
}

### 
GET http://localhost:3003/post/32926d04-01f9-4889-8cec-abd9fd01c6b5
Authorization: {{token}}