@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImIwM2M1YzVhLWU4MDQtNDVkMi05MDViLTk1ZWFmMjFiNDE0ZiIsImlhdCI6MTY1NzIwNTcxNSwiZXhwIjoxNjU3MjA5MzE1fQ.rs3FMyK3k8a6ZoV2DCNuaM7bTlnaD6-c5AUGcQYnD10

POST http://localhost:3003/user/signup
 Content-Type: application/json

 {
    "name":"Mariana",
    "email":"mari@gmail.com",
    "password":"07071999"
 } 

###

POST http://localhost:3003/user/login
 Content-Type: application/json

 {
    "email":"mari@gmail.com",
    "password":"07071999"
 } 

###
POST http://localhost:3003/post
Authorization: {{token}}
Content-Type: application/json

{
   "photo": "https://i.pinimg.com/564x/07/6a/94/076a94289a55c284c3b31c451b12442e.jpg",
   "description": "flower in the sea",
   "type": "event",
   "author_id": "f73cdb13-e4bc-4c07-9930-241a264e4241"
}

### 
GET http://localhost:3003/post/c2175c79-1554-4077-9eb8-cd6adb96e698
Authorization: {{token}}