POST http://localhost:3003/buyer
Content-Type: application/json

{
    "name": "Matheus",
    "email": "matheus@gmail.com", 
    "CPF": "12343215687"
}

### 
POST http://localhost:3003/client
Content-Type: application/json